name: Create Release

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.release.outputs.tag_name }}
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: python
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json

  build-and-push-latest-image:
    needs: [create-release]
    if: ${{ needs.create-release.outputs.release_created }}
    permissions:
      contents: read
      id-token: write
      packages: write
      attestations: write
    uses: ./.github/workflows/build-and-push-to-ghcr.yml
    with:
      image_tags: latest,${{ needs.create-release.outputs.tag }}
    secrets: inherit
